<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NUnit" Version="5.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Gens.Art/Gens.Art.csproj" />
    <ProjectReference Include="../../src/Gens.Application/Gens.Application.csproj" />
    <ProjectReference Include="../../src/Gens.Portraits/Gens.Portraits.csproj" />
    <ProjectReference Include="../../src/Gens.Graphics.Skia/Gens.Graphics.Skia.csproj" />
    <ProjectReference Include="../../src/Gens.Graphics/Gens.Graphics.csproj" />
  </ItemGroup>
</Project>
