using Gens.Simulation.Characters;
using Gens.Simulation.Commands;
using Gens.Simulation.Identity;
using Gens.Simulation.State;
using Gens.Simulation.Time;

namespace Gens.Simulation.Chronicle;

/// <summary>Pins or unpins an entry (§7): "the player can elevate any entry's personal visibility
/// regardless of its assigned tier, without changing what any other system reads that tier
/// as."</summary>
public sealed record SetChronicleEntryPinnedCommand(
    RuntimeId<Command> CommandId,
    string ActorId,
    GameDate SubmittedDate,
    string? CausationId,
    RuntimeId<ChronicleEntry> EntryId,
    bool Pinned) : ICommand;

/// <summary>The validate/mutate pipeline for <see cref="SetChronicleEntryPinnedCommand"/> (ADR 0006).</summary>
public static class SetChronicleEntryPinnedCommands
{
    public static readonly ValidationErrorCode EntryNotFound = new("chronicle.setPinned.entryNotFound");

    public static readonly CommandPipeline<WorldState, SetChronicleEntryPinnedCommand> Pipeline = new(
        validate: Validate,
        mutate: Mutate,
        issueSequenceNumber: static state => state.IssueCommandSequenceNumber());

    private static ValidationErrorCode? Validate(WorldState state, SetChronicleEntryPinnedCommand command) =>
        state.ChronicleEntries.TryGet(command.EntryId, out _) ? null : EntryNotFound;

    private static IDomainEvent[] Mutate(WorldState state, SetChronicleEntryPinnedCommand command)
    {
        state.ChronicleEntries.TryGet(command.EntryId, out var entry);
        state.ChronicleEntries.Remove(command.EntryId);
        state.ChronicleEntries.Add(command.EntryId, entry with { Pinned = command.Pinned });

        return new IDomainEvent[]
        {
            new ChronicleEntryPinnedChangedEvent(
                state.EventIds.Issue(), command.SubmittedDate, command.EntryId, command.Pinned, command.CommandId.ToTaggedString()),
        };
    }
}

/// <summary>Attaches or clears a free-text annotation on an entry (§7: "a free-text note the player
/// can attach to any entry"). <see cref="Annotation"/> of <c>null</c> clears an existing one.</summary>
public sealed record AnnotateChronicleEntryCommand(
    RuntimeId<Command> CommandId,
    string ActorId,
    GameDate SubmittedDate,
    string? CausationId,
    RuntimeId<ChronicleEntry> EntryId,
    string? Annotation) : ICommand;

/// <summary>The validate/mutate pipeline for <see cref="AnnotateChronicleEntryCommand"/> (ADR 0006).</summary>
public static class AnnotateChronicleEntryCommands
{
    public static readonly ValidationErrorCode EntryNotFound = new("chronicle.annotate.entryNotFound");

    public static readonly CommandPipeline<WorldState, AnnotateChronicleEntryCommand> Pipeline = new(
        validate: Validate,
        mutate: Mutate,
        issueSequenceNumber: static state => state.IssueCommandSequenceNumber());

    private static ValidationErrorCode? Validate(WorldState state, AnnotateChronicleEntryCommand command) =>
        state.ChronicleEntries.TryGet(command.EntryId, out _) ? null : EntryNotFound;

    private static IDomainEvent[] Mutate(WorldState state, AnnotateChronicleEntryCommand command)
    {
        state.ChronicleEntries.TryGet(command.EntryId, out var entry);
        state.ChronicleEntries.Remove(command.EntryId);
        state.ChronicleEntries.Add(command.EntryId, entry with { PlayerAnnotation = command.Annotation });

        return new IDomainEvent[]
        {
            new ChronicleEntryAnnotatedEvent(
                state.EventIds.Issue(), command.SubmittedDate, command.EntryId, command.CommandId.ToTaggedString()),
        };
    }
}

/// <summary>Adds a player-authored diary-style entry directly (§7: "a lightweight personal note entry
/// type the player can add directly — not generated by any system, a pure diary-style addition").</summary>
public sealed record AddChronicleNoteCommand(
    RuntimeId<Command> CommandId,
    string ActorId,
    GameDate SubmittedDate,
    string? CausationId,
    RuntimeId<Household> HouseholdId,
    string Prose,
    ChronicleCategory Category,
    IReadOnlyList<RuntimeId<Character>> LinkedCharacterIds) : ICommand;

/// <summary>The validate/mutate pipeline for <see cref="AddChronicleNoteCommand"/> (ADR 0006).</summary>
public static class AddChronicleNoteCommands
{
    public static readonly ValidationErrorCode ProseRequired = new("chronicle.addNote.proseRequired");

    public static readonly CommandPipeline<WorldState, AddChronicleNoteCommand> Pipeline = new(
        validate: Validate,
        mutate: Mutate,
        issueSequenceNumber: static state => state.IssueCommandSequenceNumber());

    private static ValidationErrorCode? Validate(WorldState state, AddChronicleNoteCommand command) =>
        string.IsNullOrWhiteSpace(command.Prose) ? ProseRequired : null;

    private static IDomainEvent[] Mutate(WorldState state, AddChronicleNoteCommand command)
    {
        var entryId = state.ChronicleEntryIds.Issue();
        var entry = new ChronicleEntry(
            entryId,
            command.HouseholdId,
            command.SubmittedDate,
            command.Category,
            ChronicleTier.Notable,
            command.Prose,
            command.LinkedCharacterIds,
            "chronicle.playerNote",
            ChronicleEntrySource.PlayerNote);
        state.ChronicleEntries.Add(entryId, entry);

        return new IDomainEvent[]
        {
            new ChronicleNoteAddedEvent(
                state.EventIds.Issue(), command.SubmittedDate, entryId, command.HouseholdId, command.CommandId.ToTaggedString()),
        };
    }
}
