namespace Gens.Simulation.Clientela;

/// <summary>Versioned constants for Phase 12 item 2's Clientela/Influence/Salutatio/poaching mechanics
/// (<c>gens-politics-patronage-design.md</c> §4), matching <see
/// cref="Reputation.ReputationCatalog"/>'s identical "numeric sizing is unsized/tunable, but must live
/// in one named place" convention — §12's Open Questions explicitly leaves every one of these figures
/// unsized against real playtest data.</summary>
public static class ClientelaCatalog
{
    /// <summary>How many months must pass between two favors called in from the same client before a
    /// second call-in stops reading as "too often without reciprocation" (§4.2). A call-in inside this
    /// window costs opinion via <see cref="OverdrawnOpinionPenalty"/>.</summary>
    public const int FavorCooldownMonths = 12;

    /// <summary>The opinion cost (client's opinion of patron) of an "overdrawn" favor call-in — §4.2's
    /// "a favor drawn on too often without reciprocation costs the relationship-web opinion between
    /// patron and client".</summary>
    public const int OverdrawnOpinionPenalty = -8;

    /// <summary>Influence generated per client per month, before the quality bonus below (§4.4:
    /// "generated by Clientela roster size and quality").</summary>
    public const int InfluencePerClient = 1;

    /// <summary>The average opinion (patron-facing) a roster needs to earn the quality bonus below.</summary>
    public const int InfluenceQualityOpinionThreshold = 25;

    /// <summary>Extra monthly Influence for a roster whose average opinion clears <see
    /// cref="InfluenceQualityOpinionThreshold"/> — the "quality," not just "size," half of §4.4's
    /// generation formula.</summary>
    public const int InfluenceQualityBonus = 3;

    /// <summary>Extra monthly Influence per currently-held <see cref="Magistracies.MagistracyRecord"/>
    /// — §4.4's "plus held office" clause.</summary>
    public const int InfluencePerActiveOffice = 5;

    /// <summary>Influence lost per month regardless of generation — §4.4's "a stockpile left unspent
    /// slowly decays." Applied before that month's generation, so a roster that just started producing
    /// Influence this tick doesn't also decay it away in the same tick (matching <see
    /// cref="Reputation.FavorExpirationSystem"/>'s "the tick that just happened doesn't also age out"
    /// shape in spirit, not this system's own <see cref="Reputation.FavorObligation"/> mechanism).
    /// Floored at zero — see <see cref="InfluenceResolver.Apply"/>.</summary>
    public const int InfluenceDecayPerMonth = 2;

    /// <summary>Minimum roster size for a Salutatio to read as "well-attended" (§4.3).</summary>
    public const int SalutatioWellAttendedMinClients = 3;

    /// <summary>Minimum roster average opinion (of the patron) for a Salutatio to read as
    /// "well-attended" (§4.3) — a large roster of resentful clients still doesn't count.</summary>
    public const int SalutatioWellAttendedMinAvgOpinion = 20;

    /// <summary>Dignitas gained from a well-attended Salutatio, applied through <see
    /// cref="Reputation.AdjustDignitasCommand"/> per that item's own "the one command path every
    /// future Dignitas-moving system routes through."</summary>
    public const int SalutatioWellAttendedDignitasGain = 3;

    /// <summary>Influence gained from a well-attended Salutatio, applied directly via <see
    /// cref="InfluenceResolver.Apply"/> — Influence has no equivalent shared command yet (nothing else
    /// writes it), so unlike the Dignitas half there is no existing primitive to route through.</summary>
    public const int SalutatioWellAttendedInfluenceGain = 2;

    /// <summary>Dignitas cost of a neglected Salutatio (§4.3) — any non-empty roster that fails the
    /// well-attended bar above. A patron with zero clients holds no Salutatio at all and pays nothing;
    /// this is a cost for holding court badly, not for not holding it.</summary>
    public const int SalutatioNeglectedDignitasCost = 2;

    /// <summary>The Ambition floor (§4.5's Core Condition stat, 0-100) above which a client is a real
    /// poaching risk.</summary>
    public const int PoachingHighAmbitionThreshold = 70;

    /// <summary>The Loyalty ceiling (0-100) below which a client is a real poaching risk.</summary>
    public const int PoachingLowLoyaltyThreshold = 30;

    /// <summary>How long a client can go without a favor called in (or, if never called, since
    /// recruitment) before "favors keep going unrewarded" (§4.5) applies.</summary>
    public const int PoachingOverdrawnAfterMonths = 18;

    /// <summary>Percent chance per month a poaching-eligible client (high Ambition, low Loyalty,
    /// overdrawn, and a real rival available — see <see cref="ClientPoachingSystem"/>'s own doc
    /// comment) actually flips this tick.</summary>
    public const int PoachingChancePercent = 15;
}
