using Gens.Simulation.Characters;
using Gens.Simulation.Commands;
using Gens.Simulation.Identity;
using Gens.Simulation.Magistracies;
using Gens.Simulation.State;
using Gens.Simulation.Time;

namespace Gens.Simulation.Clientela;

/// <summary>
/// The monthly Influence generation-and-decay tick (Phase 12 item 2; §4.4): "generated by Clientela
/// roster size and quality... plus held office," and "a stockpile left unspent slowly decays." Decay
/// is applied first, then generation, so a roster that starts producing Influence this same tick isn't
/// also decayed away in it (mirroring, in spirit, <see cref="ClientelaCatalog.InfluenceDecayPerMonth"/>'s
/// own doc comment). Runs in <see cref="TickPhase.RelationshipsActors"/>, the same phase <see
/// cref="Reputation.FavorExpirationSystem"/> and <see cref="SalutatioSystem"/> run in.
///
/// <b>Scope note:</b> §4.4's "a stockpile left unspent" framing implies tracking actual usage
/// (a favor called in, an election contested) and only decaying an untouched stockpile. No per-resource
/// "last spent" timestamp exists for Influence, and inventing one duplicates state this item doesn't
/// otherwise need — this system instead applies a flat monthly decay to every household with a stored
/// Influence balance, spent or not, then regenerates from that month's roster/office standing. The net
/// effect matches §4.4's real intent (Influence trends toward whatever a roster/office currently
/// supports rather than banking indefinitely) without a bespoke usage ledger.
/// </summary>
public sealed class InfluenceCycleSystem : IMonthlySystem<WorldState>
{
    public string Id => "clientela.influenceCycle";
    public TickPhase Phase => TickPhase.RelationshipsActors;
    public IReadOnlyCollection<string> Reads { get; } = new[] { "clientelaEntries", "relationships", "characters", "magistracyRecords", "householdInfluences" };
    public IReadOnlyCollection<string> Writes { get; } = new[] { "householdInfluences" };
    public IReadOnlyCollection<string> Prerequisites { get; } = Array.Empty<string>();

    public IReadOnlyList<IDomainEvent> Tick(WorldState state, MonthlyTickContext context)
    {
        if (state is null)
            throw new ArgumentNullException(nameof(state));

        // Decay every existing balance first — materialize the key set, since InfluenceResolver.Apply
        // mutates state.HouseholdInfluences mid-scan otherwise.
        foreach (var householdId in state.HouseholdInfluences.InAscendingOrder().Select(entry => entry.Key).ToArray())
            InfluenceResolver.Apply(state, householdId, -ClientelaCatalog.InfluenceDecayPerMonth);

        foreach (var patronHouseholdId in ClientelaResolver.PatronsWithClients(state))
        {
            var clients = ClientelaResolver.ClientsOf(state, patronHouseholdId);
            if (clients.Count == 0)
                continue;

            var generation = clients.Count * ClientelaCatalog.InfluencePerClient;
            if (!state.HouseholdHeadships.TryGet(patronHouseholdId, out var headship))
            {
                InfluenceResolver.Apply(state, patronHouseholdId, generation);
                continue;
            }

            var averageOpinion = AverageOpinionOfPatron(state, headship!.HeadCharacterId, clients);
            if (averageOpinion >= ClientelaCatalog.InfluenceQualityOpinionThreshold)
                generation += ClientelaCatalog.InfluenceQualityBonus;

            generation += MagistracyResolver.ActiveOfficeCountForHousehold(state, patronHouseholdId) * ClientelaCatalog.InfluencePerActiveOffice;

            InfluenceResolver.Apply(state, patronHouseholdId, generation);
        }

        // A quiet resource trickle, matching RelationshipDecaySystem's identical "silent background
        // drift, not an event-worthy occurrence" precedent — nothing downstream needs a per-tick event
        // for a number that already reads directly off InfluenceResolver.
        return Array.Empty<IDomainEvent>();
    }

    private static double AverageOpinionOfPatron(WorldState state, RuntimeId<Character> patronHeadId, IReadOnlyList<ClientelaEntry> clients)
    {
        var total = 0;
        foreach (var client in clients)
            total += state.Relationships.TryGet(new RelationshipKey(client.ClientId, patronHeadId), out var relationship)
                ? relationship.Opinion
                : 0;
        return (double)total / clients.Count;
    }
}
