using Gens.Simulation.Queries;

namespace Gens.Simulation.Fame;

/// <summary>Versioned constants for Phase 12 item 8's Fame mechanics
/// (<c>gens-celebrities-influential-figures-design.md</c>), matching <see
/// cref="Scandal.ScandalCatalog"/>'s identical "unsized against real playtest data, but named in one
/// place" convention — §11's Open Questions explicitly leaves "all numeric sizing" unresolved.</summary>
public static class FameCatalog
{
    /// <summary>§2/Games &amp; Spectacle §2's "decays slowly if genuinely inactive" — the flat monthly
    /// decay <see cref="FameDecaySystem"/> applies to every stored <see cref="CharacterFame"/> balance,
    /// matching <see cref="Clientela.ClientelaCatalog.InfluenceDecayPerMonth"/>'s identical "a flat
    /// monthly decay on every stored balance, regenerated by whatever real generation exists" shape —
    /// though, unlike Influence, no real generation source is wired by this item (see <see
    /// cref="AdjustFameCommand"/>'s own doc comment), so decay is presently the only thing that ever
    /// moves an untouched <see cref="CharacterFame"/> balance.</summary>
    public const int DecayPerMonth = 2;

    /// <summary>§2's Fame/Dignitas Divergence reading (<see cref="FameDivergenceQuery"/>): the Fame
    /// score above which a Character counts as genuinely "Famous" for divergence purposes, rather than
    /// merely present in the field.</summary>
    public const int FamousFameThreshold = 40;

    /// <summary>§2's divergence reading: the household Dignitas at or above which a Character's own
    /// household counts as "respected" for divergence purposes, below which it counts as the
    /// non-respected half of the same binary — a real, if simple, proxy for §2's own "famous and
    /// disreputable at once" in a codebase where no Infamia status exists yet to check directly (Crime
    /// &amp; Punishment §13, Romance, Sexuality &amp; Lineage §13, both Phase 17, unbuilt) — see <see
    /// cref="FameDivergenceQuery"/>'s own doc comment for why this single threshold, not a stand-in
    /// Infamia flag or a three-way band, is this item's real, reasoned choice.</summary>
    public const int RespectedDignitasThreshold = 20;

    /// <summary>§5's endorsement mechanic (<see cref="Magistracies.HoldContestedElectionCommand"/>):
    /// the Fame score an endorsing Character must clear for "a sufficiently Famous individual's public
    /// endorsement" to actually move the needle — a Character below this line is not yet the "crowd
    /// that loves a famous charioteer" §5 describes.</summary>
    public const int EndorsementFameThreshold = 50;

    /// <summary>§5's endorsement bonus itself — the flat score bonus a Character above <see
    /// cref="EndorsementFameThreshold"/> lends the candidate they publicly favor, matching <see
    /// cref="Magistracies.MagistracyCatalog.FactionAlignmentBonus"/>'s identical "a flat thumb on the
    /// scale" shape for the same election-scoring formula.</summary>
    public const int EndorsementScoreBonus = 10;
}
